### ISSUE TITLE
Chart no longer working

### ISSUE THREAD

**Issue by Thumpxr** [Splo0sh/netdata_ts3_plugin#18]
Since 29.11 the ts3chart is no longer working.

Netdata version: v1.19.0-90-nightly
TS3 Version: 3.10.2

logfile netdata.err prints
`python.d ERROR: ts3[local] : No data received.`
and occassionally
`python.d ERROR: ts3[local] : invalid literal for int() with base 10: ''`

**Comment by Thumpxr** [comment]
Debugging the ts3.chart.py results in this:

`/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace ts3
2019-12-19 15:45:05: python.d INFO: plugin[main] : using python v2
2019-12-19 15:45:05: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2019-12-19 15:45:05: python.d DEBUG: plugin[main] : loading '/etc/netdata/python.d.conf'
2019-12-19 15:45:05: python.d DEBUG: plugin[main] : '/etc/netdata/python.d.conf' is loaded
2019-12-19 15:45:05: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2019-12-19 15:45:05: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2019-12-19 15:45:05: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2019-12-19 15:45:05: python.d DEBUG: plugin[main] : [ts3] looking for 'ts3.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2019-12-19 15:45:05: python.d DEBUG: plugin[main] : [ts3] loading '/etc/netdata/python.d/ts3.conf'
2019-12-19 15:45:05: python.d DEBUG: plugin[main] : [ts3] '/etc/netdata/python.d/ts3.conf' is loaded
2019-12-19 15:45:05: python.d INFO: plugin[main] : [ts3] built 1 job(s) configs
2019-12-19 15:45:05: python.d DEBUG: plugin[main] : ts3[local] was previously active, applying recovering settings
2019-12-19 15:45:05: python.d DEBUG: ts3[local] : No unix socket specified. Trying TCP/IP socket.
2019-12-19 15:45:05: python.d DEBUG: ts3[local] : No TLS preference specified, not using TLS.
2019-12-19 15:45:05: python.d DEBUG: ts3[local] : No request specified. Using: "serverinfo
"
2019-12-19 15:45:05: python.d DEBUG: ts3[local] : TeamSpeak server process found. Connecting...
2019-12-19 15:45:05: python.d INFO: plugin[main] : ts3[local] : check success
CHART netdata.runtime_ts3_local '' 'Execution time for ts3_local' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
DIMENSION run_time 'run time' absolute 1 1

2019-12-19 15:45:05: python.d DEBUG: ts3[local] : started, update frequency: 1
2019-12-19 15:45:06: python.d DEBUG: ts3[local] : Creating socket to "::1", port 10011
2019-12-19 15:45:06: python.d DEBUG: ts3[local] : connecting socket to "::1", port 10011
2019-12-19 15:45:06: python.d DEBUG: ts3[local] : set socket connect timeout to: 2.0
2019-12-19 15:45:06: python.d DEBUG: ts3[local] : connected to "::1", port 10011
2019-12-19 15:45:06: python.d DEBUG: ts3[local] : TS3
Welcome to the TeamSpeak 3 ServerQuery interface, type "help" for a list of commands and "help <command>" for information on a specific command.

2019-12-19 15:45:06: python.d DEBUG: ts3[local] : error id=0 msg=ok

2019-12-19 15:45:06: python.d DEBUG: ts3[local] : error id=0 msg=ok

2019-12-19 15:45:06: python.d ERROR: ts3[local] : No data received.
2019-12-19 15:45:06: python.d ERROR: ts3[local] : Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/ts3.chart.py", line 246, in _get_data
    raw = self._get_raw_data()
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SocketService.py", line 270, in _get_raw_data
    data = self._receive(raw)
  File "/usr/libexec/netdata/python.d/ts3.chart.py", line 225, in _receive
    self.debug(str(buf))
  File "/usr/libexec/netdata/python.d/python_modules/bases/loggers.py", line 166, in debug
    'job_name': self.job_name or self.module_name})
  File "/usr/libexec/netdata/python.d/python_modules/bases/loggers.py", line 124, in debug
    self.logger.debug(' '.join(map(unicode_str, msg)), **kwargs)
  File "/usr/libexec/netdata/python.d/python_modules/bases/collection.py", line 98, in unicode_str
    return unicode(arg)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 340: ordinal not in range(128)

2019-12-19 15:45:06: python.d DEBUG: ts3[local] : get_data() returned no data
2019-12-19 15:45:06: python.d DEBUG: ts3[local] : update => [FAILED] (elapsed time: -, failed retries in a row: 1)
2019-12-19 15:45:07: python.d DEBUG: ts3[local] : nnection_bytes_sent_keepalive=2713995 connection_packets_received_keepalive=66182 connection_bytes_received_keepalive=2779670 connection_packets_sent_control=10854 connection_bytes_sent_control=2365017 connection_packets_received_control=10876 connection_bytes_received_control=1009780 connection_packets_sent_total=164943 connection_bytes_sent_total=17887702 connection_packets_received_total=520107 connection_bytes_received_total=101454036 connection_bandwidth_sent_last_second_total=817 connection_bandwidth_sent_last_minute_total=1909 connection_bandwidth_received_last_second_total=25129 connection_bandwidth_received_last_minute_total=25647
error id=0 msg=ok

2019-12-19 15:45:07: python.d DEBUG: ts3[local] : [('', '', '817', '', '', '', '', '', '', ''), ('', '', '', '25129', '', '', '', '', '', '')]
2019-12-19 15:45:07: python.d ERROR: ts3[local] : invalid literal for int() with base 10: ''
2019-12-19 15:45:07: python.d ERROR: ts3[local] : Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/ts3.chart.py", line 276, in _get_data
    connected_users = int(regex[0][0]) - int(regex[1][1])
ValueError: invalid literal for int() with base 10: ''

2019-12-19 15:45:07: python.d DEBUG: ts3[local] : get_data() returned no data
2019-12-19 15:45:07: python.d DEBUG: ts3[local] : update => [FAILED] (elapsed time: -, failed retries in a row: 2)
2019-12-19 15:45:08: python.d ERROR: ts3[local] : No data received.
2019-12-19 15:45:08: python.d ERROR: ts3[local] : Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/ts3.chart.py", line 246, in _get_data
    raw = self._get_raw_data()
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SocketService.py", line 270, in _get_raw_data
    data = self._receive(raw)
  File "/usr/libexec/netdata/python.d/ts3.chart.py", line 225, in _receive
    self.debug(str(buf))
  File "/usr/libexec/netdata/python.d/python_modules/bases/loggers.py", line 166, in debug
    'job_name': self.job_name or self.module_name})
  File "/usr/libexec/netdata/python.d/python_modules/bases/loggers.py", line 124, in debug
    self.logger.debug(' '.join(map(unicode_str, msg)), **kwargs)
  File "/usr/libexec/netdata/python.d/python_modules/bases/collection.py", line 98, in unicode_str
    return unicode(arg)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 340: ordinal not in range(128)`

**Comment by coraxx** [comment]
Thank you for the log! I will probably be able to look at it next week. Hold tight :)

**Comment by Thumpxr** [comment]
Works again. Probably a netdata issue...
